package com.addy.contus.entity;

public interface PdfTextData {
	
	public String getResult();
	public String getResultStatement1();
	public String getResultStatement2();
	public String getScore();
	public String getHigh();
	public String getLow();
	public String getNeutral();
	public String getVeryHigh();
	public String getVeryLow();
	public String getFacetN();
	public String getnDef();
	public String getnHigh();
	public String getnLow();
	public String getnNeutral();
	public String getnInfo();
	public String getFacetN1();
	public String getN1Info();
	public String getFacetN2();
	public String getN2Info();
	public String getFacetN3();
	public String getN3Info();
	public String getFacetN4();
	public String getN4Info();
	public String getFacetN5();
	public String getN5Info();
	public String getFacetN6();
	public String getN6Info();
	public String getFacetE();
	public String geteDef();
	public String geteHigh();
	public String geteLow();
	public String geteNeutral();
	public String geteInfo();
	public String getFacetE1();
	public String getE1Info();
	public String getFacetE2();
	public String getE2Info();
	public String getFacetE3();
	public String getE3Info();
	public String getFacetE4();
	public String getE4Info();
	public String getFacetE5();
	public String getE5Info();
	public String getFacetE6();
	public String getE6Info();
	public String getFacetO();
	public String getoDef();
	public String getoHigh();
	public String getoLow();
	public String getoNeutral();
	public String getoInfo();
	public String getFacetO1();
	public String getO1Info();
	public String getFacetO2();
	public String getO2Info();
	public String getFacetO3();
	public String getO3Info();
	public String getFacetO4();
	public String getO4Info();
	public String getFacetO5();
	public String getO5Info();
	public String getFacetO6();
	public String getO6Info();
	public String getFacetA();
	public String getaDef();
	public String getaHigh();
	public String getaLow();
	public String getaNeutral();
	public String getaInfo();
	public String getFacetA1();
	public String getA1Info();
	public String getFacetA2();
	public String getA2Info();
	public String getFacetA3();
	public String getA3Info();
	public String getFacetA4();
	public String getA4Info();
	public String getFacetA5();
	public String getA5Info();
	public String getFacetA6();
	public String getA6Info();
	public String getFacetC();
	public String getcDef();
	public String getcHigh();
	public String getcLow();
	public String getcNeutral();
	public String getcInfo();
	public String getFacetC1();
	public String getC1Info();
	public String getFacetC2();
	public String getC2Info();
	public String getFacetC3();
	public String getC3Info();
	public String getFacetC4();
	public String getC4Info() ;
	public String getFacetC5() ;
	public String getC5Info();
	public String getFacetC6();
	public String getC6Info() ;
	
	

}
